# Generated by Django 4.0.5 on 2022-06-22 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_sotr'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(db_index=True, max_length=50, verbose_name='Курс')),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('th_group', models.CharField(max_length=100, verbose_name='Группа')),
                ('th_date', models.DateField(verbose_name='Дата')),
                ('th_time', models.TimeField(verbose_name='Время')),
                ('th_audit', models.CharField(max_length=100, verbose_name='Аудитория')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='department.tablecat')),
            ],
            options={
                'verbose_name': 'Таблица',
                'verbose_name_plural': 'Таблицы',
            },
        ),
    ]
