# Generated by Django 4.0.5 on 2022-06-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_remove_sotr_patronymic_remove_sotr_surname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_user', models.CharField(default='', max_length=15)),
                ('Subject', models.CharField(max_length=120)),
                ('Teacher', models.CharField(max_length=120)),
                ('type_of_week', models.CharField(choices=[('Четная', 'Четная'), ('Нечетная', 'Нечетная'), ('Еженедельно', 'Еженедельно')], default='Еженедельно', max_length=20)),
                ('day_of_week', models.CharField(choices=[('1Понедельник', 'Понедельник'), ('2Вторник', 'Вторник'), ('3Среда', 'Среда'), ('4Четверг', 'Четверг'), ('5Пятница', 'Пятница'), ('6Суббота', 'Суббота')], default='1Понедельник', max_length=20)),
                ('time_of_day', models.CharField(choices=[('1', 'Первая'), ('2', 'Вторая'), ('3', 'Третья'), ('4', 'Четвертая'), ('5', 'Пятая'), ('6', 'Шестая')], default='1', max_length=1)),
                ('Classes', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='tables',
            name='cat',
        ),
        migrations.DeleteModel(
            name='TableCat',
        ),
        migrations.DeleteModel(
            name='Tables',
        ),
    ]
